In [1]:
import pandas as pd

# Carga el archivo CSV
df = pd.read_csv('data/sample3.1.csv', encoding='ISO-8859-1')

# Reemplaza los espacios vacíos con NaN
df.replace('', pd.NA, inplace=True)

# Elimina las columnas con más de un 50% de datos faltantes
df.dropna(axis=1, thresh=df.shape[0]*0.5, inplace=True)

# Elimina las filas con más de un 50% de datos faltantes
df.dropna(axis=0, thresh=df.shape[1]*0.5, inplace=True)


df.dropna(inplace=True)
# Tratamiento de valores atípicos para columnas numéricas
for col in df.select_dtypes(include=['float64', 'int64']).columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Opción 1: Elimina valores atípicos
    df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]


# Guarda el dataframe limpio a un nuevo archivo CSV
df.to_csv('data/sample3.1_cleaned.csv', index=False)

df = pd.read_csv('data/sample3.1_cleaned.csv', encoding='ISO-8859-1')

df

,Country,Region,DataYear,ClassGrade,Gender,Ageyears,Handed,Height_cm,Footlength_cm,Armspan_cm,...,Watching_TV_Hours,Paid_Work_Hours,Work_At_Home_Hours,Schoolwork_Pressure,Planned_Education_Level,Favorite_Music,Superpower,Preferred_Status,Role_Model_Type,Charity_Donation
0,USA,CA,2012,12,Male,17.0,Right-Handed,178,25,178,...,2,0,2,A lot,Graduate degree,Pop,Fly,Happy,Relative,Health
1,USA,CA,2013,12,Female,17.0,Right-Handed,165,24,160,...,14,0,0,Some,Graduate degree,Other,Freeze time,Happy,Relative,Health
2,USA,CA,2017,12,Male,17.0,Right-Handed,196,29.68,201,...,4,3,2,Some,Graduate degree,Country,Fly,Happy,Sports person,"Arts, culture, sports"
3,USA,CA,2019,12,Female,17.0,Right-Handed,168,24,168,...,0,0,1,Very little,Graduate degree,Other,Freeze time,Healthy,Business person,Environment
4,USA,CA,2016,12,Female,17.0,Right-Handed,170,23,168,...,0,0,5,Very little,Graduate degree,Pop,Telepathy,Happy,Relative,Health
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,USA,CA,2022,11,Female,16.0,Ambidextrous,4.11,4.10,7.5,...,10,10,10,Some,Graduate degree,Reggae,Invisibility,Healthy,Friend,International aid
202,USA,CA,2023,11,Male,16.0,Right-Handed,180,11.67,183,...,6,0,2,Some,Graduate degree,Rap/Hip hop,Freeze time,Healthy,Friend,"Wildlife, animals"
203,USA,CA,2021,12,Male,17.0,Right-Handed,172.7,22.86,171.2,...,0,0,5,Some,Graduate degree,Jazz,Telepathy,Happy,Musician or singer,Environment
204,USA,CA,2012,12,Male,16.0,Right-Handed,160,23,151,...,9,0,3,A lot,Graduate degree,Other,Freeze time,Happy,Relative,Health
205,USA,CA,2014,11,Male,17.0,Right-Handed,169,26,170,...,15,0,2,Some,Other,Rap/Hip hop,Invisibility,Famous,Other,International aid

In [2]:
df.shape

(206, 60)

In the first dataset we have 206 rows of data after cleaning, so we will need another data sample in order to concatenate them and complete the 300 rows in total (after cleaning)

In [3]:
import pandas as pd

# Carga el archivo CSV
df = pd.read_csv('data/sample3.2.csv', encoding='ISO-8859-1')

# Reemplaza los espacios vacíos con NaN
df.replace('', pd.NA, inplace=True)

# Elimina las columnas con más de un 50% de datos faltantes
df.dropna(axis=1, thresh=df.shape[0]*0.5, inplace=True)

# Elimina las filas con más de un 50% de datos faltantes
df.dropna(axis=0, thresh=df.shape[1]*0.5, inplace=True)


df.dropna(inplace=True)
# Tratamiento de valores atípicos para columnas numéricas
for col in df.select_dtypes(include=['float64', 'int64']).columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Opción 1: Elimina valores atípicos
    df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]


# Guarda el dataframe limpio a un nuevo archivo CSV
df.to_csv('data/sample3.2_cleaned.csv', index=False)

df = pd.read_csv('data/sample3.2_cleaned.csv', encoding='ISO-8859-1')

df

,Country,Region,DataYear,ClassGrade,Gender,Ageyears,Handed,Height_cm,Footlength_cm,Armspan_cm,...,Watching_TV_Hours,Paid_Work_Hours,Work_At_Home_Hours,Schoolwork_Pressure,Planned_Education_Level,Favorite_Music,Superpower,Preferred_Status,Role_Model_Type,Charity_Donation
0,USA,CA,2012,12,Male,17.0,Right-Handed,178,25,178,...,2,0,2,A lot,Graduate degree,Pop,Fly,Happy,Relative,Health
1,USA,CA,2013,12,Female,17.0,Right-Handed,165,24,160,...,14,0,0,Some,Graduate degree,Other,Freeze time,Happy,Relative,Health
2,USA,CA,2017,12,Male,17.0,Right-Handed,196,29.68,201,...,4,3,2,Some,Graduate degree,Country,Fly,Happy,Sports person,"Arts, culture, sports"
3,USA,CA,2019,12,Female,17.0,Right-Handed,168,24,168,...,0,0,1,Very little,Graduate degree,Other,Freeze time,Healthy,Business person,Environment
4,USA,CA,2016,12,Female,17.0,Right-Handed,170,23,168,...,0,0,5,Very little,Graduate degree,Pop,Telepathy,Happy,Relative,Health
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,USA,CA,2022,11,Female,16.0,Ambidextrous,4.11,4.10,7.5,...,10,10,10,Some,Graduate degree,Reggae,Invisibility,Healthy,Friend,International aid
202,USA,CA,2023,11,Male,16.0,Right-Handed,180,11.67,183,...,6,0,2,Some,Graduate degree,Rap/Hip hop,Freeze time,Healthy,Friend,"Wildlife, animals"
203,USA,CA,2021,12,Male,17.0,Right-Handed,172.7,22.86,171.2,...,0,0,5,Some,Graduate degree,Jazz,Telepathy,Happy,Musician or singer,Environment
204,USA,CA,2012,12,Male,16.0,Right-Handed,160,23,151,...,9,0,3,A lot,Graduate degree,Other,Freeze time,Happy,Relative,Health
205,USA,CA,2014,11,Male,17.0,Right-Handed,169,26,170,...,15,0,2,Some,Other,Rap/Hip hop,Invisibility,Famous,Other,International aid

We have 412 rows of data in total, so we can now concatenate the cleaned data in one single sample with 300 rows of data

In [4]:
import pandas as pd

# Carga los archivos CSV
df1 = pd.read_csv('data/sample3.1_cleaned.csv', encoding='ISO-8859-1')
df2 = pd.read_csv('data/sample3.2_cleaned.csv', encoding='ISO-8859-1')


# Concatena los DataFrames
df_concatenado = pd.concat([df1, df2], ignore_index=True)

# Limita el DataFrame concatenado a las primeras 300 filas
df_limitado = df_concatenado.head(300)

# Guarda el DataFrame limitado en un nuevo archivo CSV
df_limitado.to_csv('data/sample3.csv', index=False)

# Imprime la información del DataFrame limitado
#print(f"El archivo limitado tiene {df_limitado.shape[0]} filas y {df_limitado.shape[1]} columnas.")
df = pd.read_csv('data/sample3.csv', encoding='ISO-8859-1')
df

,Country,Region,DataYear,ClassGrade,Gender,Ageyears,Handed,Height_cm,Footlength_cm,Armspan_cm,...,Watching_TV_Hours,Paid_Work_Hours,Work_At_Home_Hours,Schoolwork_Pressure,Planned_Education_Level,Favorite_Music,Superpower,Preferred_Status,Role_Model_Type,Charity_Donation
0,USA,CA,2012,12,Male,17.0,Right-Handed,178,25,178,...,2,0,2,A lot,Graduate degree,Pop,Fly,Happy,Relative,Health
1,USA,CA,2013,12,Female,17.0,Right-Handed,165,24,160,...,14,0,0,Some,Graduate degree,Other,Freeze time,Happy,Relative,Health
2,USA,CA,2017,12,Male,17.0,Right-Handed,196,29.68,201,...,4,3,2,Some,Graduate degree,Country,Fly,Happy,Sports person,"Arts, culture, sports"
3,USA,CA,2019,12,Female,17.0,Right-Handed,168,24,168,...,0,0,1,Very little,Graduate degree,Other,Freeze time,Healthy,Business person,Environment
4,USA,CA,2016,12,Female,17.0,Right-Handed,170,23,168,...,0,0,5,Very little,Graduate degree,Pop,Telepathy,Happy,Relative,Health
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,USA,CA,2020,12,Female,17.0,Right-Handed,172,24,172,...,2,0,1,A lot,Graduate degree,Rhythm and blues (R&B),Telepathy,Happy,Relative,Environment
296,USA,CA,2021,11,Female,18.0,Right-Handed,170.1,25.5,12.7,...,7,0,21,Some,Graduate degree,Other,Telepathy,Healthy,Politician,Environment
297,USA,CA,2014,12,Female,16.0,Right-Handed,167,24,157,...,2,1,5,A lot,Graduate degree,Other,Freeze time,Happy,Musician or singer,"Arts, culture, sports"
298,USA,CA,2021,11,Female,16.0,Right-Handed,147,23,155,...,2,0,5,Some,Graduate degree,Rap/Hip hop,Super strength,Happy,Relative,Health
299,USA,CA,2012,12,Male,17.0,Left-Handed,202,20,2000,...,0,0,0,Some,Graduate degree,Rock and roll,Freeze time,Happy,Other,Education/Youth development

In [16]:
df.shape

(300, 60)

Now we have the sample of 300 rows of data from California students, cleaned and ready to concatenate with the samples from other states